# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/brunch
image: node:8.5.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm update
  - npm install -g brunch
  - npm install -g babel-brunch
  - npm install -g babel-preset-react
  - brunch build --production
  artifacts:
    paths:
    - public
  only:
  - master
