# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/brunch
image: node:8.5.0

pages:
  environment: prod
  cache:
    paths:
    - node_modules/

  script:
  - npm update
  - npm install -g brunch
  - npm install
  - brunch build --production
  artifacts:
    paths:
    - public
  only:
  - master

testing:
  environment: stage
  cache:
    paths:
    - test/node_modules/

  script:
  - npm update
  - npm install -g brunch
  - npm install
  - brunch build --production
  artifacts:
    paths:
    - test/public
  except:
  - master